name: Create and publish a Docker image

on:
  push:
    branches: ['dev']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: "${{ REGISTRY }}/${{ github.repository }}/image-name"
  VERSION: ${{ github.run_number }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:

      # Action will create and boot a builder using by default 
      # the docker-container builder driver
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: --debug
      
      # Login action will take care to log in against a GitHub registry.
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: docker_build 
        uses: docker/build-push-action@v2
        with:
          file: ./docker/Dockerfile
          tags: ${{ env.IMAGE_NAME }}:v.0.${{ env.VERSION }}
          push: true
