---
name: Deploy docker image

on:
  push:
    branches: ['main']

env:
  IMAGE_NAME: "ghcr.io/${{ github.repository }}/mask"
  REMOTE_USER: "root"
  REMOTE_HOST: "cumerun.fun"
  PREFIX: "макс "
  CHANNEL: "855739037762846760"
  REGISTRY: ghcr.io
  VERSION: ${{ github.run_number }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:

      # Buildx setup
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: --debug

      # Login to GitHub registry.
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Push docker image GitHub registry.
      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: ./docker/Dockerfile
          tags: ${{ env.IMAGE_NAME }}:v.0.${{ env.VERSION }}
          push: ${{ github.event_name != 'pull_request' }}


  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout project
        uses: actions/checkout@v2

      - name: Deploy docker-compose

        uses: wshihadeh/docker-deployment-action@v1
        with:
          remote_docker_host: "${{ env.REMOTE_USER }}@${{ env.REMOTE_HOST }}"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
          deployment_mode: docker-compose
          deploy_path: /var/mask
          stack_file_name: docker-compose.yaml
          keep_files: 5
          args: environment  TOKEN=${{ secrets.TOKEN }} \
                             PREFIX=${{ env.PREFIX }} \
                             CHANNEL=${{ env.CHANNEL }}
